### ISSUE TITLE
Cross origin problem in PhantomJS outer context

### ISSUE THREAD

**Issue by formido** [skeeto/skewer-mode#51]
There's a longstanding bug in the PhantomJS REPL where you can't request any sites[1], so I wanted to see if I can get a good workflow going with skewer-mode and PhantomJS for doing interactive web scraping and iteratively building up scripts, including sessions that span many pages.

First things first, can we retrieve the skewer script from PhantomJS's outer context? When I run the script here:

https://gist.github.com/formido/a13d7bcb813513e3b7df/8c61394fd4ac03af72e0058f4392fdd0f372c4f9

...this is the output:

```
XMLHttpRequest cannot load http://localhost:8080/skewer. Origin file:// is not allowed by Access-Control-Allow-Origin.
GET http://localhost:8080/skewer
XHR Error!
status: 0 ()
body:


GET http://updates.html5rocks.com
XHR Loaded
status: 200 (OK)
body size: 96289


XMLHttpRequest cannot load http://www.google.com/. Origin file:// is not allowed by Access-Control-Allow-Origin.
GET http://www.google.com
XHR Error!
status: 0 ()
body:
```

http://updates.html5rocks.com implements CORS and we can reach it OK, but PhantomJS fails trying to reach the skewer script. Any ideas?
1. ariya/phantomjs/issues/11180

**Comment by Samba-Konduri** [comment]
im getting the bellow error 
NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'http://localhost:5080/master-data/customers/!@#$%^&*()_+/entities'.

even i tried with   the blow options , any idea ?
 '--web-security': 'yes',
                    '--local-to-remote-url-access': 'yes',
                    '--ignore-ssl-errors' : 'true'
