### ISSUE TITLE
Skewering from external sites

### ISSUE THREAD

**Issue by psibi** [skeeto/skewer-mode#53]
As written in the README file, using greasemonkey I injected the user.js file into the external site. But the problem is I'm not able to connect `skewer-repl` with those external sites. When I type anything in `skewer-repl`, it goes only to the `http://127.0.0.1:8080/skewer/demo`.

How do I  make skewer-repl communicate with external site ?

**Comment by kostafey** [comment]
Ok. looks like more documentation notes required. For example, I have an application running in `localhost:8080`.

The steps to communicate to this "external" site.

1. `(setq httpd-port 8081)`
2. Install `greasemonkey` for Firefox or `tampermonkey` for Chrome.
3. Add skewer-everything.user.js script.
4. Modify this script: `var host = 'http://localhost:8081'`;
5. `M-x run-skewer` (get new tab for `localhost:8081`)
6. `M-x skewer-repl`
7. Reload target "external" `localhost:8080`
8. At this point, I'll get 2 clients in skewer-repl. So I have to close my `localhost:8081` tab.

Now, `skewer-repl` works as expected. Is it a correct way?

Is it possible to create only one client (for `localhost:8080`) immediately?
