### ISSUE TITLE
autocompletion in Skewer REPL

### ISSUE THREAD

**Issue by nchurch** [skeeto/skewer-mode#59]
So I was able to get autocompletion working with tern-mode and company-tern in Javascript buffers, but this does not work in the Skewer REPL.  Any idea why this might be?

**Comment by hatschipuh** [comment]
Hi, I have the same problem...Would really be nice to have a solution for that.

**Comment by unhammer** [comment]
As a quick workaround, you can use `company-dabbrev-code`:

```
  (defun my-company-flow-setup ()
    (set (make-local-variable 'company-backends)
         '(company-dabbrev-code)))
  (add-hook #'skewer-repl-mode-hook #'my-company-flow-setup)
(add-to-list 'company-dabbrev-code-modes #'comint-mode)
(setq company-dabbrev-code-other-buffers 'code)
```
