### ISSUE TITLE
How do I get skewer-mode to work with web-mode

### ISSUE THREAD

**Issue by thepreacher** [skeeto/skewer-mode#61]
I've been trying get skewer-mode to work in web-mode by adding something like 
```(add-hook 'web-mode-hook 'skewer-html-mode)``` It doesn't work however when I do C-M-x, I get the message ```No Javascript AST available```.

**Comment by skeeto** [comment]
Skewer depends on js2-mode's JavaScript parser, so it can only be used with js2-mode as major mode. I don't believe web-mode is compatible with js2-mode, and so, if true, Skewer isn't compatible with web-mode.

**Comment by thepreacher** [comment]
Oh I see. Thanks anyway for a wonderful tool. I hope to find a way to use it in the future.
