### ISSUE TITLE
syncing between html source and rendered page

### ISSUE THREAD

**Issue by DrWaleedAYousef** [skeeto/skewer-mode#68]
I have two question regarding the issue:

1- can I sync between the html source (in the emacs buffer) and the rendered page as in AUCTEX. For example, I want to click on the code it takes me to the rendered position and vice versa.

2- Can i render to an emacs window (not to an external browser) for simple html files.

**Comment by skeeto** [comment]
Skewer can only connect to ("skewer") a live browser page running
JavaScript (ES5 or later). Running it through some sort of HTML-to-X
converter won't quality, nor would rendering in Emacs (no JavaScript).
These are both outside Skewer's scope.

As a non-Skewer alternative for the former: If you're using a PDF viewer
that automatically follows changes in the file (Evince is a good choice
for this), try setting up a "M-x compile"-friendly build for your
document (Makefile, etc.). When you perform the build, you'll see the
changes immediately reflected in the adjacent PDF viewer. That's how I
work on PDF documents myself (Pandoc/LaTeX).

**Comment by wyousef** [comment]
Thanks so much for your reply,

What about rendering plain html (no javascript) into emacs (two buffers sdie-by-side)?

**Comment by skeeto** [comment]
That would be relatively easy to do ever since Emacs got its HTML
renderer, eww. It's probably like 30 lines of code. But it's still
outside of the scope of Skewer, since Skewer is all about interacting
with a live page.

**Comment by DrWaleedAYousef** [comment]
Thanks so much
