### ISSUE TITLE
Warnings in Chromium

### ISSUE THREAD

**Issue by ramblehead** [skeeto/skewer-mode#72]
Thank you for the excellent mode! It was easy to setup and in many cases it can replace mozrepl off the shelf.

One small observation at Chromium console:

```
'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead. skewer:496
'webkitIndexedDB' is deprecated. Please use 'indexedDB' instead. skewer:496
```

**Comment by skeeto** [comment]
I don't know what would cause this, because Skewer doesn't touch any
storage. Line 496 is also beyond the end of the default script. Perhaps
you have hook function on skewer-js-hook that's injecting more code?

**Comment by ramblehead** [comment]
It seems that those warnings only occur when doing autocompletion with ac-js2 mode with ac-js2-evaluate-calls set to t. The following is a screenshot of the chromium debugger window:

![screenshot from 2016-09-20 16-20-39](https://cloud.githubusercontent.com/assets/2130398/18688925/65f491d8-7f7e-11e6-8c8c-e45627e869f5.png)

Apologie for the confusion - browser reports those warnings as they were comming from skewer - thus I reported it here :)

**Comment by skeeto** [comment]
I see the issue. In ac-js2, `obj` is bound to `window` (or more generally the global object) and, to discover completions, it's mechanically touching all its keys, setting off the warnings.

> Apologies for the confusion - browser reports those warnings as they were coming from skewer - thus I reported it here :)

No problem. I'd rather get a mistaken bug report than no bug report for a real bug.
