### ISSUE TITLE
Is the default keybinding working as intended?

### ISSUE THREAD

**Issue by computersarecool** [skeeto/skewer-mode#77]
When I use this skewer, and type something like

`document.body.style.color = 'white'` 

and evaluate it with `C-x C-e` only the `'white'` gets evaluated.  It seems like I have to use the `C-M-x` keybinding, but, in reading the documentation, it seems like `skewer-eval-last-expression` is what I want (it is also much more convenient).

Am I doing something wrong, or is there a time when we would want this functionality?

**Comment by skeeto** [comment]
Put a semicolon at the end and place the point right after the
semicolon. This is due to ambiguity: What if you really wanted to
evaluate the 'white' part of the expression? The semicolon disambiguates
that, selecting the entire line as an expression.

Plus it's a lot more sanitary. :-)

**Comment by computersarecool** [comment]
Ah, fair enough.
The Standard JS style causing a small problem here. Thanks for the package and the feedback!
