### ISSUE TITLE
Simplify & add to docs to communicate to the "external" site

### ISSUE THREAD

**Issue by kostafey** [skeeto/skewer-mode#82]
For example, there is an application running on `localhost:8080`.

The steps to communicate to this "external" site.
1. (setq httpd-port 8081) in `.emacs`
2. Install `greasemonkey` for Firefox or `tampermonkey` for Chrome.
3. Add `skewer-everything.user.js` script.
4. Modify this script: 
```javascript
var host = 'http://localhost:8081';
```
5. M-x `run-skewer` (get new tab for localhost:8081)
6. M-x `skewer-repl`
7. Reload target "external" `localhost:8080 tab` in browser
8. At this point, you'll get 2 clients in skewer-repl. So you have to close localhost:8081 tab.

Is there are any simpler way?

**Comment by skeeto** [comment]
Greasemonkey/Tampermonkey is only necessary for the userscript, which 
itself isn't necessary just to use Skewer. The run-skewer command 
already injects Skewer into the page, and you can include the script in 
any pages you control. The only steps you care about in this case are in 
the README under "Manual version."

**Comment by kostafey** [comment]
Oh, really. Thank you. But if you **need** to reload original `localhost:8080`, you will get 2 results any time you run js code (one from original "remote" `localhost:8080`, other from plain js process) until you close skewer `localhost:8081` tab.
