### ISSUE TITLE
ReferenceError: skewerNativeXHR is not defined

### ISSUE THREAD

**Issue by DoMiNeLa10** [skeeto/skewer-mode#83]
Whenever I try to run skewer, I get the following error:
```
skewer:36 Uncaught ReferenceError: skewerNativeXHR is not defined
    at Function.skewer.getJSON (skewer:36)
    at skewer (skewer:27)
skewer:54 Uncaught ReferenceError: skewerNativeXHR is not defined
    at Function.skewer.postJSON (skewer:54)
    at skewer.error (skewer:397)
```
This happens no matter if I run skewer with my config, or if I start Emacs without any configuration (`emacs -q`) and then load all required files manually.

**Comment by skeeto** [comment]
I missed this problem in #81. Thanks!
